# You can use this to store API keys, mail server settings,
# or any other kind of configuration data that your application needs.
# In order to keep your production settings secret, store the production
# copy of this file on your server under shared/config/config.yml and copy
# it on deployment with this Capistrano task:#

# task :copy_config_files do
#   filename = "config/config.yml"
#   run "cp #{shared_path}/#{filename} #{release_path}/#{filename}"
# end
# after "deploy:update_code", :copy_config_files

development: &non_production_settings
  encryption_key: "\xC1\x1D\x19\x10\xAB\xF4*\x81\x85C\xD0\xE7z\xDD>\x89"

  :carrier_wave:
    :storage: :file
  :mailer:
    :address: smtp.gmail.com  # C ror_ecommerce
    :domain: 'gmail.com'
    :port: 587
    :user_name: clickplus1@gmail.com  # C ror_ecommerce
    :password: 'some_cooler_password'          # C ror_ecommerce
    :authentication: :plain
    :enable_starttls_auto: true
    :perform_deliveries: true
    :default_url_options:
       :host: 'localhost:3000'

test:
  <<: *non_production_settings
production:
  encryption_key: "\xC1\x1D\x19\x10\xAB\xF4*\x81\x85C\xD0\xE7z\xDD>\x89"
  :carrier_wave:
    :storage: :file
  :mailer:
    :address: smtp.gmail.com  # C ror_ecommerce
    :domain: 'gmail.com'
    :port: 587
    :user_name: clickplus1@gmail.com  # C ror_ecommerce
    :password: 'some_cool_password'       # C ror_ecommerce
    :authentication: :plain
    :enable_starttls_auto: true
    :perform_deliveries: true
    :default_url_options:
       :host: 'clickplus.herokuapp.com'
