# You can use this to store API keys, mail server settings,
# or any other kind of configuration data that your application needs.
# In order to keep your production settings secret, store the production
# copy of this file on your server under shared/config/config.yml and copy
# it on deployment with this Capistrano task:#

# task :copy_config_files do
#   filenames = %w(kimbra_studio sensitive)
#   filenames.each do |file|
#     run "cp #{shared_path}/#{filename} #{release_path}/config/#{filename}"
#   end
# end
# after "deploy:update_code", :copy_config_files

development: &non_production_settings
  encryption_key: "\xC1\x1D\x19\x10\xAB\xF4*\x81\x85C\xD0\xE7z\xDD>\x89"
  :s3:
    bucket_name: kimbra-development
    access_key_id:
    secret_access_key:
  :carrier_wave:
    :storage: :fog
    :dump_image: true
  :mailer:
    :address: smtp.gmail.com
    :domain: 'gmail.com'
    :port: 587
    :user_name: clickplus1@gmail.com
    :password:
    :authentication: :plain
    :enable_starttls_auto: true
    :perform_deliveries: true
    :default_url_options:
       :host: 'localhost:3000'
  :stripe:
    :name: clickplus1@gmail.com
    :secret_key: '4osP7DgGMXX3Z4CWgkvT5q3EPBldxfss'
    :publishable_key: 'pk_T5rlG8nj6zwCgBOHUmXTbRGcSdDXs'
  :click_face:
    api_key:
    api_secret:
    website:
      username: 'clickplus1'
      info:     'facerul3s'
    :value:
    :secret_key:

test:
  <<: *non_production_settings

production:
  encryption_key: "\xC1\x1D\x19\x10\xAB\xF4*\x81\x85C\xD0\xE7z\xDD>\x89"
  :s3:
    bucket_name: kimbra-studio
    access_key_id:
    secret_access_key:
  :carrier_wave:
    :storage: :fog
    :dump_image: false
  :mailer:
    :address: smtp.gmail.com
    :domain: 'gmail.com'
    :port: 587
    :user_name: clickplus1@gmail.com
    :password:
    :authentication: :plain
    :enable_starttls_auto: true
    :perform_deliveries: true
    :default_url_options:
       :host: 'www.KimbraClickPLUS.com'
  :stripe:
    :name: clickplus1@gmail.com
    :secret_key:
    :publishable_key:
  :click_face:
    api_key:
    api_secret:
    website:
      username: 'clickplus1'
      info:     'facerul3s'
